rsa_mk_coding:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql:///rsa_construction?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
      username: root
      password: root
      pro-username: local_root
      pro-password: ACMDOTCPPINNERPURITY,@163.COM.CN.AUTHENTICARION
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5t6jSdZbaCJsjUxs8fsy
    access-key-secret: frU0i5stSlAAOIlXlAV5YrgKaqtc8y
    bucket-name: innerpurity-bucket
  jwt:
    secret-key: innerpurity
    ttl: 7200000
    token-name: token
  app-jwt:
    ttl: 2419200000
